apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: yr7k81zbm-nodejs
  janus-idp.io/tekton: yr7k81zbm-nodejs
  backstage.io/kubernetes-id: yr7k81zbm-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: yr7k81zbm-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
