apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: yr7k81zbm-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: yr7k81zbm-nodejs 
  name: yr7k81zbm-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: yr7k81zbm-nodejs 
